<?php
if($path==='directory'&&$method==='GET'){
 $locations=rows('SELECT id,name,enabled FROM locations WHERE organization_id=?',[org()]);$accounts=rows('SELECT id,username,location_id FROM accounts WHERE organization_id=? AND enabled=1',[org()]);json_out(['locations'=>$locations,'accounts'=>$accounts]);
}
if($path==='admin/readiness'&&$method==='GET'){role(['administrator']);$checks=['php'=>PHP_VERSION,'pdo_mysql'=>extension_loaded('pdo_mysql'),'fileinfo'=>extension_loaded('fileinfo'),'openssl'=>extension_loaded('openssl'),'gd'=>extension_loaded('gd'),'imagick'=>extension_loaded('imagick'),'zip'=>extension_loaded('zip'),'media_writable'=>is_writable($config['media_dir']),'https'=>($_SERVER['HTTPS']??'')==='on','upload_max_filesize'=>ini_get('upload_max_filesize'),'post_max_size'=>ini_get('post_max_size'),'database'=>query('SELECT VERSION()')->fetchColumn(),'migrations'=>rows('SELECT * FROM schema_migrations ORDER BY version')];json_out($checks);}
if($path==='admin/organization'){
 role(['administrator']);if($method==='GET')json_out(one('SELECT * FROM organizations WHERE id=?',[org()]));if($method==='POST'){if(!in_array($body['timezone']??'',DateTimeZone::listIdentifiers(),true))fail(422,'Invalid timezone');begin_write();query('UPDATE organizations SET name=?,timezone=?,settings=? WHERE id=?',[substr($body['name']??'',0,200),$body['timezone'],encoded($body['settings']??[]),org()]);audit('organization_update',org());$pdo->commit();json_out(['ok'=>true]);}
}
if(preg_match('#^admin/(accounts|locations|devices|audit)$#',$path,$matches)){
 role(['administrator']);$kind=$matches[1];
 if($method==='GET'){$columns=['accounts'=>'id,organization_id,location_id,username,category,role,can_create_templates,enabled','locations'=>'*','devices'=>'*','audit'=>'*'][$kind];$table=$kind==='audit'?'audit_log':$kind;$limit=$kind==='audit'?' ORDER BY id DESC LIMIT 500':'';json_out(['rows'=>rows("SELECT $columns FROM $table WHERE organization_id=?$limit",[org()])]);}
 if($method==='POST'){
  $id=require_id($body['id']??'');begin_write();
  $collision=one("SELECT organization_id FROM $kind WHERE id=?",[$id]);if($collision&&$collision['organization_id']!==org())fail(404,'Record unavailable');
  if($kind==='accounts'){
   $old=one('SELECT * FROM accounts WHERE organization_id=? AND id=?',[org(),$id]);$category=$body['category']??'individual';$role=$body['role']??'';$location=$category==='location'?require_id($body['location_id']??''):null;
   if(!in_array($role,['administrator','content_manager','report_viewer','location'],true)||!in_array($category,['individual','location'],true)||($category==='location')!==($role==='location'))fail(422,'Invalid role');
   if($old&&($old['category']!==$category||$old['location_id']!==$location))fail(422,'Account category and location are permanent. Create a new account.');if($location)location_scope($location);
   if($id===actor()['id']&&($role!=='administrator'||empty($body['enabled'])))fail(422,'Cannot disable or demote your active administrator account');
   $password=$body['password']??'';if(!$old||$password!==''){if(strlen($password)<12||strlen($password)>1024)fail(422,'Use a password of at least 12 characters');$hash=password_hash($password,PASSWORD_DEFAULT);}else $hash=$old['password_hash'];
   $username=trim($body['username']??'');$collision=one('SELECT id FROM accounts WHERE username=?',[$username]);if($collision&&$collision['id']!==$id)fail(409,'Username unavailable');if(strlen($username)<1||strlen($username)>190)fail(422,'Username required');
   query('INSERT INTO accounts(id,organization_id,location_id,username,password_hash,category,role,can_create_templates,enabled) VALUES(?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE username=VALUES(username),password_hash=VALUES(password_hash),role=VALUES(role),can_create_templates=VALUES(can_create_templates),enabled=VALUES(enabled)',[$id,org(),$location,$username,$hash,$category,$role,(int)($body['can_create_templates']??($category==='location')),(int)($body['enabled']??true)]);
   if($old&&($password!==''||!($body['enabled']??true)))query('DELETE FROM sessions WHERE organization_id=? AND account_id=?',[org(),$id]);
  }elseif($kind==='locations'){query('INSERT INTO locations(id,organization_id,name,enabled) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),enabled=VALUES(enabled)',[$id,org(),substr($body['name']??'',0,200),(int)($body['enabled']??true)]);change('locations',$id);}
  elseif($kind==='devices'){if(!one('SELECT id FROM devices WHERE organization_id=? AND id=?',[org(),$id]))fail(404,'Device unavailable');query('UPDATE devices SET revoked=?,name=? WHERE organization_id=? AND id=?',[(int)($body['revoked']??false),substr($body['name']??'Browser',0,200),org(),$id]);if(!empty($body['revoked']))query('DELETE FROM sessions WHERE organization_id=? AND device_id=?',[org(),$id]);}
  else fail(405,'Read-only resource');
  audit('admin_'.$kind,$id);query('UPDATE organizations SET permission_epoch=sequence+1,sequence=sequence+1 WHERE id=?',[org()]);$pdo->commit();json_out(['ok'=>true]);
 }
}
if($path==='admin/storage'){
 role(['administrator']);if($method==='GET')json_out(['rows'=>rows('SELECT id,name,mime,byte_size,width,height,archived,created_at FROM media_assets WHERE organization_id=? ORDER BY byte_size DESC',[org()]),'limit'=>$config['max_storage_bytes']]);
 if($method==='POST'){$id=require_id($body['id']??'');begin_write();$r=one('SELECT * FROM media_assets WHERE organization_id=? AND id=?',[org(),$id]);if(!$r)fail(404,'Image unavailable');if(($body['action']??'')==='delete'){$refs=0;foreach(['records','record_versions','meetings'] as $table)foreach(rows("SELECT payload FROM $table WHERE organization_id=?",[org()]) as $ref)if(str_contains($ref['payload'],$id))$refs++;if($refs)fail(409,'Image has historical or current references. Archive it instead.');if(empty($r['archived']))fail(409,'Archive before deleting');query('DELETE FROM media_assets WHERE organization_id=? AND id=?',[org(),$id]);change('assets',$id);audit('media_delete',$id);$pdo->commit();@unlink($r['stored_path']);if($r['thumbnail_path'])@unlink($r['thumbnail_path']);}else{query('UPDATE media_assets SET archived=1 WHERE organization_id=? AND id=?',[org(),$id]);change('assets',$id);audit('media_archive',$id);$pdo->commit();}json_out(['ok'=>true]);}
}
if(str_starts_with($path,'admin/reports/')&&$method==='GET'){
 role(['administrator','content_manager','report_viewer']);$type=substr($path,14);$args=[org()];$where='organization_id=?';
 if(!empty($_GET['location'])){$where.=' AND location_id=?';$args[]=require_id($_GET['location']);}
 if(!empty($_GET['from'])){$where.=' AND occurred_at_utc>=?';$args[]=gmdate('Y-m-d H:i:s',strtotime($_GET['from'])?:0);}
 if(!empty($_GET['to'])){$where.=' AND occurred_at_utc<=?';$args[]=gmdate('Y-m-d H:i:s',strtotime($_GET['to'].' 23:59:59')?:0);}
 $events=array_map('payload',rows("SELECT payload FROM usage_events WHERE $where ORDER BY occurred_at_utc",$args));
 if($type==='safety')$result=array_values(array_filter($events,fn($e)=>$e['event_type']==='content_presented'&&($e['content_type']??'')==='external-video'&&!empty($e['safety'])));
 elseif($type==='skips')$result=array_values(array_filter($events,fn($e)=>in_array($e['event_type'],['broadcast_skipped','slide_skipped'],true)));
 elseif($type==='content'){$counts=[];foreach($events as $e){if($e['event_type']!=='content_presented')continue;$key=$e['location_id'].':'.$e['content_id'].':'.($e['content_version']??0);if(!isset($counts[$key]))$counts[$key]=['id'=>$key,'content_id'=>$e['content_id'],'title'=>$e['title'],'version'=>$e['content_version'],'location_id'=>$e['location_id'],'presentations'=>0,'last_presented'=>''];$counts[$key]['presentations']++;$counts[$key]['last_presented']=max($counts[$key]['last_presented'],$e['occurred_at_utc']);}$result=array_values($counts);}
 elseif($type==='meetings'){$query='SELECT payload FROM meetings WHERE organization_id=?';$ma=[org()];if(!empty($_GET['location'])){$query.=' AND location_id=?';$ma[]=$_GET['location'];}$result=array_map('payload',rows($query.' ORDER BY created_at DESC',$ma));}
 elseif($type==='locations'){$result=rows('SELECT l.id,l.name,(SELECT MAX(m.created_at) FROM meetings m WHERE m.organization_id=l.organization_id AND m.location_id=l.id AND m.status=\'completed\') last_meeting,(SELECT MAX(d.last_sync) FROM devices d JOIN accounts a ON a.organization_id=d.organization_id AND a.id=d.account_id WHERE a.organization_id=l.organization_id AND a.location_id=l.id) last_sync,(SELECT COUNT(*) FROM devices d JOIN accounts a ON a.organization_id=d.organization_id AND a.id=d.account_id WHERE a.organization_id=l.organization_id AND a.location_id=l.id AND d.revoked=0 AND d.last_seen>DATE_SUB(UTC_TIMESTAMP(),INTERVAL 30 DAY)) active_devices FROM locations l WHERE l.organization_id=?',[org()]);}
 elseif(in_array($type,['broadcasts','requirements'],true)){$result=[];foreach(rows('SELECT payload FROM records WHERE organization_id=? AND kind=?',[org(),'broadcasts']) as $r){$b=payload($r);if($type==='requirements'&&$b['importance']!=='required')continue;foreach(rows('SELECT id,name FROM locations WHERE organization_id=?',[org()]) as $l){if(!empty($b['locations'])&&!in_array($l['id'],$b['locations'],true))continue;$shown=array_filter($events,fn($e)=>($e['broadcast_id']??'')===$b['id']&&$e['location_id']===$l['id']&&$e['event_type']==='broadcast_presented');$skips=array_filter($events,fn($e)=>($e['broadcast_id']??'')===$b['id']&&$e['location_id']===$l['id']&&$e['event_type']==='broadcast_skipped');$successful=array_filter($shown,fn($p)=>!array_filter($skips,fn($s)=>$s['meeting_id']===$p['meeting_id']&&($s['slide_id']??null)===($p['slide_id']??null)));$result[]=['id'=>$b['id'].':'.$l['id'],'broadcast'=>$b['title'],'location'=>$l['name'],'presented'=>count($shown),'skipped'=>count($skips),'status'=>count($successful)>0?'Presented':'Not completed','reasons'=>implode(' | ',array_column($skips,'reason'))];}}}
 else $result=$events;
 json_out(['rows'=>$result]);
}
