const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');const fs=require('fs');const crypto=require('crypto');const fixture=JSON.parse(fs.readFileSync('/tmp/mmb-e2e-fixture.json'));
(async()=>{let browser,browser2;const checks=[];const ok=(n,t)=>{assert.ok(t,n);checks.push(n);console.log('PASS',n)};try{browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process','--disable-gpu']});const errors=[];const adminContext=await browser.newContext();const p=await adminContext.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8081');await p.getByLabel('Username',{exact:true}).fill(fixture.users[0].username);await p.getByLabel('Password',{exact:true}).fill(fixture.password);await p.getByRole('button',{name:'Sign in',exact:true}).click();await p.locator('.start-panel').waitFor();await p.getByRole('button',{name:'Company workspace',exact:true}).click();await p.getByRole('button',{name:'templates',exact:true}).last().click();await p.getByRole('button',{name:'Install DTB starter libraries and daily template',exact:true}).click();await p.getByRole('button',{name:'Manage',exact:true}).first().waitFor();ok('admin installs recovered DTB starter through UI',true);
// Merge a valid MVP-format ZIP with image bytes through the actual import screen.
await p.getByRole('button',{name:'Back to meeting builder',exact:true}).click();
const backupState=await p.evaluate(async()=>structuredClone(await MMB.repository.load()));
const legacyImage=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAAAHUlEQVR4nGOU9M5jIBcwka1zVPOo5lHNo5qpohkASx8A+rXaktMAAAAASUVORK5CYII=','base64');
const legacyHash=crypto.createHash('sha256').update(legacyImage).digest('hex');const legacyAssetId=crypto.randomUUID();const legacyItemId=crypto.randomUUID();
backupState.assets.push({id:legacyAssetId,hash:legacyHash,mime:'image/png',size:legacyImage.length,name:'Legacy image.png',createdAt:new Date().toISOString()});
backupState.items.push({...backupState.items[0],id:legacyItemId,title:'Legacy imported photo',type:'image',assetId:legacyAssetId});
const {zipSync,strToU8}=require('fflate');const legacyZip=zipSync({'manifest.json':strToU8(JSON.stringify({format:'dtb-morning-meeting',version:1,appVersion:'0.1.0',exportedAt:new Date().toISOString(),state:backupState})),['assets/'+legacyHash]:legacyImage});
await p.getByRole('button',{name:'Backup & restore',exact:true}).first().click();await p.locator('input[type=file]').setInputFiles({name:'legacy-mvp.zip',mimeType:'application/zip',buffer:Buffer.from(legacyZip)});
await p.getByRole('button',{name:'Merge content',exact:true}).waitFor();ok('hosted full replacement disabled',await p.locator('option[value="replace"]').evaluate(el=>el.disabled));
await p.getByRole('button',{name:'Merge content',exact:true}).click();await p.getByText('Content merged. Local history and location preserved.',{exact:true}).waitFor();
const imported=await p.evaluate(async(id)=>{const data=await(await fetch('./api/v1/content')).json();return data.records.find(r=>r.id===id)},legacyItemId);
ok('MVP image import uploads and remaps protected media',imported?.assetId&&imported.assetId!==legacyAssetId);
const auth=await p.evaluate(async()=>{return await (await fetch('./api/v1/auth/session')).json()});const headers={'Origin':'http://127.0.0.1:8081','X-CSRF-Token':auth.csrf};
// Small valid PNG, uploaded to the real PHP protected-media endpoint.
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAAAHUlEQVR4nGOU9M5jIBcwka1zVPOo5lHNo5qpohkASx8A+rXaktMAAAAASUVORK5CYII=','base64');const upload=await adminContext.request.post('http://127.0.0.1:8081/api/v1/media',{headers,multipart:{image:{name:'safety.png',mimeType:'image/png',buffer:png}}});const asset=await upload.json();ok('admin image upload succeeds',upload.status()===201||upload.status()===200);
const libs=await (await adminContext.request.get('http://127.0.0.1:8081/api/v1/libraries')).json();const library=libs.records.find(r=>r.name==='Safety');const now=new Date().toISOString();const content={id:crypto.randomUUID(),libraryId:library.id,title:'Clear aisle image',description:'Keep this route open for deliveries.',type:'image-text',tags:['safety'],url:'',assetId:asset.id,createdAt:now,updatedAt:now,lastUsedAt:null,useCount:0,archived:false,source:'Browser integration'};
const write=async(kind,data)=>{const r=await adminContext.request.post('http://127.0.0.1:8081/api/v1/records/batch',{headers,data:{records:[{id:data.id,kind,data,expected_version:0}]}});assert.equal(r.status(),200,await r.text());return (await r.json()).records[0].data};await write('items',content);const broadcast=await write('broadcasts',{id:crypto.randomUUID(),title:'Required aisle notice',content,status:'published',importance:'required',start:new Date(Date.now()-86400000).toISOString(),end:new Date(Date.now()+86400000).toISOString(),recurrence:'once',priority:100,slot:'Announcements',locations:[fixture.assembly]});
browser2=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process','--disable-gpu']});const locationContext=await browser2.newContext({viewport:{width:1180,height:820}});const l=await locationContext.newPage();l.on('pageerror',e=>errors.push(e.message));await l.goto('http://127.0.0.1:8081');await l.getByLabel('Username',{exact:true}).fill(fixture.users[1].username);await l.getByLabel('Password',{exact:true}).fill(fixture.password);await l.getByRole('button',{name:'Sign in',exact:true}).click();await l.locator('.start-panel').waitFor();await l.getByRole('button',{name:/Build a meeting/}).last().click();await l.getByPlaceholder('Who is leading today?').fill('Offline presenter');await l.getByText('Required aisle notice',{exact:true}).first().waitFor();ok('required broadcast inserted after location sync',true);await l.getByRole('button',{name:'Download meeting for offline use',exact:true}).click();await l.getByText('Ready offline. YouTube and external links still require internet.').waitFor();await l.getByRole('button',{name:'Save draft',exact:true}).click();await l.evaluate(()=>navigator.serviceWorker.ready);await l.reload();await l.locator('.start-panel').waitFor();await locationContext.setOffline(true);await l.reload();await l.locator('.start-panel').waitFor();
const recent=l.locator('.recent-meetings button');if(await recent.count())await recent.first().click();else await l.getByRole('button',{name:/Offline presenter/}).click();await l.getByRole('button',{name:'Start presentation',exact:true}).click();await l.waitForTimeout(500);await l.screenshot({path:'/tmp/mmb-hosted-start.png'});await l.getByRole('button',{name:'Next',exact:true}).click();await l.locator('.presentation img').first().waitFor();ok('downloaded protected image renders after offline restart',await l.locator('.presentation img').first().evaluate(img=>img.complete&&img.naturalWidth>0));l.once('dialog',d=>d.accept('Discussed later with supervisor'));await l.getByRole('button',{name:'Skip required slide with reason',exact:true}).click();l.once('dialog',d=>d.accept());await l.getByRole('button',{name:'Exit presentation',exact:true}).click();await locationContext.setOffline(false);await l.getByRole('button',{name:'Sync Now',exact:true}).click();await l.waitForTimeout(1000);await l.getByRole('button',{name:'Sync Now',exact:true}).click();await l.waitForTimeout(500);const report=await (await adminContext.request.get('http://127.0.0.1:8081/api/v1/admin/reports/skips')).json();const skips=report.rows.filter(r=>r.broadcast_id===broadcast.id);ok('offline required skip uploaded exactly once after retries',skips.length===1&&skips[0].reason==='Discussed later with supervisor');await l.screenshot({path:'/tmp/mmb-hosted-location.png'});ok('hosted browser flow has no runtime errors',errors.length===0);console.log(`Hosted browser: ${checks.length} checks passed`);fs.writeFileSync('/tmp/mmb-hosted-results.json',JSON.stringify({checks,errors},null,2));}finally{await browser2?.close();await browser?.close()}})().catch(e=>{console.error(e);process.exitCode=1});
