CREATE TABLE schema_migrations (version INT PRIMARY KEY, applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE organizations (id CHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, timezone VARCHAR(64) NOT NULL DEFAULT 'America/Los_Angeles', sequence BIGINT UNSIGNED NOT NULL DEFAULT 0, permission_epoch BIGINT UNSIGNED NOT NULL DEFAULT 0, settings JSON NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE locations (id CHAR(36) PRIMARY KEY, organization_id CHAR(36) NOT NULL, name VARCHAR(200) NOT NULL, enabled BOOLEAN NOT NULL DEFAULT 1, UNIQUE KEY(organization_id, id), FOREIGN KEY(organization_id) REFERENCES organizations(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE accounts (id CHAR(36) PRIMARY KEY, organization_id CHAR(36) NOT NULL, location_id CHAR(36) NULL, username VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, category ENUM('individual','location') NOT NULL, role ENUM('administrator','content_manager','report_viewer','location') NOT NULL, can_create_templates BOOLEAN NOT NULL DEFAULT 0, enabled BOOLEAN NOT NULL DEFAULT 1, UNIQUE KEY(organization_id,id), FOREIGN KEY(organization_id) REFERENCES organizations(id), FOREIGN KEY(organization_id,location_id) REFERENCES locations(organization_id,id), CHECK((category='location' AND location_id IS NOT NULL AND role='location') OR (category='individual' AND location_id IS NULL AND role<>'location'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE devices (id CHAR(36) PRIMARY KEY, organization_id CHAR(36) NOT NULL, account_id CHAR(36) NOT NULL, name VARCHAR(200) NOT NULL, last_seen DATETIME(6) NOT NULL, last_sync DATETIME(6) NULL, revoked BOOLEAN NOT NULL DEFAULT 0, UNIQUE KEY(organization_id,id), FOREIGN KEY(organization_id,account_id) REFERENCES accounts(organization_id,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE sessions (token_hash CHAR(64) PRIMARY KEY, organization_id CHAR(36) NOT NULL, account_id CHAR(36) NOT NULL, device_id CHAR(36) NOT NULL, csrf CHAR(64) NOT NULL, expires_at DATETIME NOT NULL, INDEX(expires_at), FOREIGN KEY(organization_id,account_id) REFERENCES accounts(organization_id,id), FOREIGN KEY(organization_id,device_id) REFERENCES devices(organization_id,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE login_attempts (bucket CHAR(64) PRIMARY KEY, attempts INT NOT NULL, window_start DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE audit_log (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, organization_id CHAR(36) NOT NULL, account_id CHAR(36) NULL, action VARCHAR(100) NOT NULL, target_id VARCHAR(100) NOT NULL, detail JSON NOT NULL, created_at DATETIME(6) NOT NULL, INDEX(organization_id,created_at), FOREIGN KEY(organization_id) REFERENCES organizations(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO schema_migrations(version) VALUES(1);
